// <auto-generated />
using System;
using Finance_api;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Finance_api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.3");

            modelBuilder.Entity("Finance_api.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Accounts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Created = new DateTime(2026, 2, 16, 22, 17, 4, 949, DateTimeKind.Utc).AddTicks(5517),
                            Email = "admin@gmail.com",
                            IsAdmin = true,
                            PasswordHash = "$2a$11$/9MvscxNTYR1KAZlLqQML.NwWzEV.68hGOovzvCGlAl1xwU87Ceey",
                            Username = "Admin"
                        });
                });

            modelBuilder.Entity("Finance_api.Arrotondamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Arrotondamenti");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Nessuno"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Arrotonda per eccesso"
                        },
                        new
                        {
                            Id = 3,
                            Nome = "Arrotonda per difetto"
                        });
                });

            modelBuilder.Entity("Finance_api.Assoggettamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Percentuale")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Assoggettamenti");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "IVA 22%",
                            Percentuale = 22.0
                        },
                        new
                        {
                            Id = 2,
                            Nome = "IVA 10%",
                            Percentuale = 10.0
                        },
                        new
                        {
                            Id = 3,
                            Nome = "IVA 4%",
                            Percentuale = 4.0
                        },
                        new
                        {
                            Id = 4,
                            Nome = "IVA Esente",
                            Percentuale = 0.0
                        });
                });

            modelBuilder.Entity("Finance_api.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CodiceFiscale")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("IBAN")
                        .HasColumnType("TEXT");

                    b.Property<string>("Indirizzo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PartitaIVA")
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefono")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Clienti");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CodiceFiscale = "ACMCFF80A01H501Z",
                            Created = new DateTime(2026, 2, 16, 22, 17, 4, 949, DateTimeKind.Utc).AddTicks(6476),
                            Email = "info@acmecorp.it",
                            IBAN = "IT60X0542811101000000123456",
                            Indirizzo = "Via Roma 1, 20100 Milano MI",
                            Nome = "Acme Corporation",
                            PartitaIVA = "12345678901",
                            Telefono = "+39 02 1234567"
                        },
                        new
                        {
                            Id = 2,
                            CodiceFiscale = "TCHSTF85B02F205W",
                            Created = new DateTime(2026, 2, 16, 22, 17, 4, 949, DateTimeKind.Utc).AddTicks(6478),
                            Email = "contact@techstart.io",
                            IBAN = "IT28W8000000292100645211151",
                            Indirizzo = "Piazza Venezia 10, 00100 Roma RM",
                            Nome = "TechStart SRL",
                            PartitaIVA = "98765432109",
                            Telefono = "+39 06 9876543"
                        },
                        new
                        {
                            Id = 3,
                            CodiceFiscale = "INNDIG90C03L219K",
                            Created = new DateTime(2026, 2, 16, 22, 17, 4, 949, DateTimeKind.Utc).AddTicks(6480),
                            Email = "admin@innovazionedigitale.com",
                            IBAN = "IT40S0760101600000000123456",
                            Indirizzo = "Corso Francia 100, 10143 Torino TO",
                            Nome = "Innovazione Digitale SpA",
                            PartitaIVA = "11223344556",
                            Telefono = "+39 011 5551234"
                        },
                        new
                        {
                            Id = 4,
                            Created = new DateTime(2026, 2, 16, 22, 17, 4, 949, DateTimeKind.Utc).AddTicks(6482),
                            Email = "billing@cloudsystems.it",
                            Indirizzo = "Via Indipendenza 8, 40121 Bologna BO",
                            Nome = "CloudSystems Italia",
                            PartitaIVA = "55667788990",
                            Telefono = "+39 051 8887766"
                        },
                        new
                        {
                            Id = 5,
                            CodiceFiscale = "DGTMKT95D04A944H",
                            Created = new DateTime(2026, 2, 16, 22, 17, 4, 949, DateTimeKind.Utc).AddTicks(6483),
                            Email = "info@digitalmarketingpro.it",
                            IBAN = "IT10N0306909606100000000123",
                            Indirizzo = "Via Toledo 256, 80134 Napoli NA",
                            Nome = "Digital Marketing Pro",
                            PartitaIVA = "99887766554",
                            Telefono = "+39 081 6655443"
                        });
                });

            modelBuilder.Entity("Finance_api.Fattura", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ArrotondamentoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AssoggettamentoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClienteId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataEmissione")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataScadenza")
                        .HasColumnType("TEXT");

                    b.Property<double>("ImponibileNetto")
                        .HasColumnType("REAL");

                    b.Property<int>("MetodoPagamentoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NumeroFattura")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TemaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TipoFattura")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("TotaleLordo")
                        .HasColumnType("REAL");

                    b.Property<int>("ValutaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ArrotondamentoId");

                    b.HasIndex("AssoggettamentoId");

                    b.HasIndex("ClienteId");

                    b.HasIndex("MetodoPagamentoId");

                    b.HasIndex("TemaId");

                    b.HasIndex("ValutaId");

                    b.ToTable("Fatture");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ArrotondamentoId = 1,
                            AssoggettamentoId = 1,
                            ClienteId = 1,
                            Created = new DateTime(2026, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataEmissione = new DateTime(2026, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataScadenza = new DateTime(2026, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImponibileNetto = 5000.0,
                            MetodoPagamentoId = 1,
                            NumeroFattura = "2026/001",
                            TemaId = 1,
                            TipoFattura = "Entrata",
                            TotaleLordo = 6100.0,
                            ValutaId = 1
                        },
                        new
                        {
                            Id = 2,
                            ArrotondamentoId = 1,
                            AssoggettamentoId = 1,
                            ClienteId = 2,
                            Created = new DateTime(2026, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataEmissione = new DateTime(2026, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataScadenza = new DateTime(2026, 2, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImponibileNetto = 3500.0,
                            MetodoPagamentoId = 1,
                            NumeroFattura = "2026/002",
                            TemaId = 3,
                            TipoFattura = "Entrata",
                            TotaleLordo = 4270.0,
                            ValutaId = 1
                        },
                        new
                        {
                            Id = 3,
                            AssoggettamentoId = 1,
                            ClienteId = 4,
                            Created = new DateTime(2026, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataEmissione = new DateTime(2026, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataScadenza = new DateTime(2026, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImponibileNetto = 1500.0,
                            MetodoPagamentoId = 1,
                            NumeroFattura = "F2026/001",
                            TemaId = 1,
                            TipoFattura = "Uscita",
                            TotaleLordo = 1830.0,
                            ValutaId = 1
                        },
                        new
                        {
                            Id = 4,
                            ArrotondamentoId = 1,
                            AssoggettamentoId = 1,
                            ClienteId = 3,
                            Created = new DateTime(2026, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataEmissione = new DateTime(2026, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataScadenza = new DateTime(2026, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImponibileNetto = 7500.0,
                            MetodoPagamentoId = 1,
                            NumeroFattura = "2026/003",
                            TemaId = 2,
                            TipoFattura = "Entrata",
                            TotaleLordo = 9150.0,
                            ValutaId = 1
                        },
                        new
                        {
                            Id = 5,
                            ArrotondamentoId = 1,
                            AssoggettamentoId = 1,
                            ClienteId = 5,
                            Created = new DateTime(2026, 2, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataEmissione = new DateTime(2026, 2, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataScadenza = new DateTime(2026, 3, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImponibileNetto = 4200.0,
                            MetodoPagamentoId = 2,
                            NumeroFattura = "2026/004",
                            TemaId = 4,
                            TipoFattura = "Entrata",
                            TotaleLordo = 5124.0,
                            ValutaId = 1
                        },
                        new
                        {
                            Id = 6,
                            AssoggettamentoId = 1,
                            ClienteId = 4,
                            Created = new DateTime(2026, 2, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataEmissione = new DateTime(2026, 2, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataScadenza = new DateTime(2026, 3, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImponibileNetto = 2000.0,
                            MetodoPagamentoId = 1,
                            NumeroFattura = "F2026/002",
                            TemaId = 1,
                            TipoFattura = "Uscita",
                            TotaleLordo = 2440.0,
                            ValutaId = 1
                        },
                        new
                        {
                            Id = 7,
                            AssoggettamentoId = 1,
                            ClienteId = 1,
                            Created = new DateTime(2026, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataEmissione = new DateTime(2026, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataScadenza = new DateTime(2026, 3, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImponibileNetto = 1200.0,
                            MetodoPagamentoId = 3,
                            NumeroFattura = "F2026/003",
                            TemaId = 2,
                            TipoFattura = "Uscita",
                            TotaleLordo = 1464.0,
                            ValutaId = 1
                        });
                });

            modelBuilder.Entity("Finance_api.Tema", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Colore")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Temi");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Colore = "#5865f2",
                            Nome = "Servizi IT"
                        },
                        new
                        {
                            Id = 2,
                            Colore = "#43b581",
                            Nome = "Consulenza"
                        },
                        new
                        {
                            Id = 3,
                            Colore = "#faa61a",
                            Nome = "Sviluppo Software"
                        },
                        new
                        {
                            Id = 4,
                            Colore = "#f04747",
                            Nome = "Design"
                        });
                });

            modelBuilder.Entity("Finance_api.TipoPagamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TipiPagamento");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Bonifico Bancario"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Carta di Credito"
                        },
                        new
                        {
                            Id = 3,
                            Nome = "PayPal"
                        },
                        new
                        {
                            Id = 4,
                            Nome = "Contanti"
                        });
                });

            modelBuilder.Entity("Finance_api.Valuta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Codice")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.Property<string>("Simbolo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Valute");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Codice = "EUR",
                            Nome = "Euro",
                            Simbolo = "€"
                        },
                        new
                        {
                            Id = 2,
                            Codice = "USD",
                            Nome = "US Dollar",
                            Simbolo = "$"
                        },
                        new
                        {
                            Id = 3,
                            Codice = "GBP",
                            Nome = "British Pound",
                            Simbolo = "£"
                        });
                });

            modelBuilder.Entity("Finance_api.Fattura", b =>
                {
                    b.HasOne("Finance_api.Arrotondamento", "Arrotondamento")
                        .WithMany("Fatture")
                        .HasForeignKey("ArrotondamentoId");

                    b.HasOne("Finance_api.Assoggettamento", "Assoggettamento")
                        .WithMany("Fatture")
                        .HasForeignKey("AssoggettamentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Finance_api.Cliente", "Cliente")
                        .WithMany("Fatture")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Finance_api.TipoPagamento", "MetodoPagamento")
                        .WithMany("Fatture")
                        .HasForeignKey("MetodoPagamentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Finance_api.Tema", "Tema")
                        .WithMany("Fatture")
                        .HasForeignKey("TemaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Finance_api.Valuta", "Valuta")
                        .WithMany("Fatture")
                        .HasForeignKey("ValutaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Arrotondamento");

                    b.Navigation("Assoggettamento");

                    b.Navigation("Cliente");

                    b.Navigation("MetodoPagamento");

                    b.Navigation("Tema");

                    b.Navigation("Valuta");
                });

            modelBuilder.Entity("Finance_api.Arrotondamento", b =>
                {
                    b.Navigation("Fatture");
                });

            modelBuilder.Entity("Finance_api.Assoggettamento", b =>
                {
                    b.Navigation("Fatture");
                });

            modelBuilder.Entity("Finance_api.Cliente", b =>
                {
                    b.Navigation("Fatture");
                });

            modelBuilder.Entity("Finance_api.Tema", b =>
                {
                    b.Navigation("Fatture");
                });

            modelBuilder.Entity("Finance_api.TipoPagamento", b =>
                {
                    b.Navigation("Fatture");
                });

            modelBuilder.Entity("Finance_api.Valuta", b =>
                {
                    b.Navigation("Fatture");
                });
#pragma warning restore 612, 618
        }
    }
}
